routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//authentication
// Route::get('manage-product','Backend\ProductController@index');
Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logoutt');
Route::post('login', 'Auth\LoginController@authenticate')->name('loginn');

//socilite
//facebook
Route::get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderFacebookCallback');
//google
Route::get('login/google', 'Auth\LoginController@redirectToGoogleProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderGoogleCallback');

//backend

//filter
Route::get('manage-product/search','Backend\ProductController@filter')->name('filter');
Route::get('manage-quotation/search','Backend\QuotationController@filter')->name('qfilter');
Route::get('filter-orders', 'Backend\OrderController@filter')->name('filter-orders');
Route::get('manage-code/search', 'Backend\CodeController@filter')->name('filter-code');
Route::get('manage-post/search', 'Backend\PostController@filter')->name('filter-post');
Route::get('manage-promotion/search','Backend\PromotionController@filter')->name('filter-promotion');

Route::get('manage-comments', 'Backend\CommentController@post_comment')->name('manage-comments');
Route::get('filter-user', 'Backend\UserController@filter')->name('filter-user');
Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::resources([
    'manage-user' => 'Backend\UserController',
    'manage-product-category' => 'Backend\ProductCategoryController',
    'manage-product' => 'Backend\ProductController',
    'manage-post-category' => 'Backend\PostCategoryController',
    'manage-post' => 'Backend\PostController',
    'manage-tag' => 'Backend\TagController',
    'manage-banner' => 'Backend\BannerController',
    'manage-code' => 'Backend\CodeController',
    'manage-order' => 'Backend\OrderController',
    'manage-quotation' => 'Backend\QuotationController',
    'manage-footer-post' => 'Backend\FooterPostController',
    'manage-comment' => 'Backend\CommentController',
    'manage-file' => 'Backend\FileController',
    'manage-promotion'=> 'Backend\PromotionController'
]);


//frontend
// Route::get('search-product', 'Frontend\ProductController@search')->name('search_product');
Route::get('','Frontend\HomeController@index')->name('index');
Route::resource('index','Frontend\HomeController');
Route::resource('danh-muc','Frontend\ProductCategoryController');
Route::resource('post','Frontend\PostController');
Route::resource('san-pham','Frontend\ProductController');
Route::resource('cart','Backend\CartController');
Route::resource('order','Backend\OrderDetailController');
Route::resource('user','Frontend\UserController');
Route::resource('don-hang','Frontend\OrderController');
Route::resource('address','Backend\AddressController');
Route::resource('code','Frontend\CodeController');
Route::resource('manage-address','Frontend\AddressController');
Route::resource('footer-post','Frontend\FooterPostController');
Route::resource('tag','Frontend\TagController');
//quotation 
Route::resource('yeu-cau-bao-gia','Frontend\QuotationController');

Route::get('dia-chi','Backend\AddressController@create');
Route::get('tao-dia-chi','Backend\AddressController@createAddress');
Route::post('save-address','Backend\AddressController@storeAddressOnly');

Route::get('filter-order', 'Frontend\OrderController@filter')->name('filter-order');
Route::get('filter-product-cate/{id}', 'Frontend\ProductCategoryController@filter')->name('filter-product-cate');
Route::get('search', 'Frontend\HomeController@search')->name('search-product');
Route::post('filter-search', 'Frontend\HomeController@filterSearch')->name('filter-search');

//comments for post
Route::post('comments', 'Frontend\CommentController@store')->name('comment');

Route::post('comment-product', 'Frontend\CommentController@product')->name('comment-product');

Route::get('check-cart', 'Frontend\CheckcartController@index')->name('check-cart');
Route::get('list-cart', 'Frontend\CheckcartController@show')->name('list-cart');

Route::post('reply', 'Frontend\ReplyController@store')->name('reply');

Route::post('saving-data','Backend\AddressController@store');
Route::post('saving-order','Backend\AddressController@save');
Route::get('thanh-toan','Backend\AddressController@index');
Route::get('get-district-list','Backend\AddressController@getDistrictList');
Route::get('get-ward-list','Backend\AddressController@getWardList');



//change user password by themselve
Route::post('update-password','Frontend\UserController@updatePassword')->name('update-password');

//export data user 
Route::get('export', 'Backend\ExportController@export')->name('export');
Route::get('export-order', 'Backend\ExportOrderController@export')->name('export-order');
Route::get('export-product', 'Backend\ExportProductController@export')->name('export-product');
Route::get('export-code', 'Backend\ExportCodeController@export')->name('export-code');

app/Http/Controllers/Frontend/AddressController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Address;
use App\Models\Cart;
use App\Models\Province;
use App\Models\FooterPost;
use App\Models\District;
use App\Models\Ward;
use App\Models\Tag;
use App\Models\ProductCategory;
use Illuminate\Support\Facades\Auth;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::check())
        {
            $footerPost = FooterPost::where('status',1)->get();
            $address = Address::findOrFail($id);
            $provinces = Province::pluck("name","id");
            $cartlist = Cart::where('user_id',Auth::user()->id)->count();
            $cart = Cart::where('user_id',Auth::user()->id)->get();

            //hotTags in index
            $tags = Tag::all()->sortByDesc('views')->take(6);
            //hot tags in footer
            $tgs = Tag::all()->sortByDesc('views')->take(12);
            
            //get all active categogies
            $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                            ->OrderBy('order','desc')->get();
            
            return view('frontend.editAddress',compact('tags','tgs','categories','cart','cartlist','address','provinces','footerPost'));
        }
        return redirect()->route('index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::check())
        {
            //validate
            $request->validate([
                'phone' => ['regex:/(01[2|6|8|9]|03[2|3|4|5|6|7|8|9]|05[6|8|9]|08[1|2|3|4|5|6|9|8]|09[0|1|2|3|4|2|6|7|8|9])+([0-9]{7})\b/']
            ]);
            
            //create address
            $province = Province::where('id',$request->get('province'))->first()->name;
            $district = District::where('id',$request->get('district'))->first()->name;
            $ward = Ward::where('id',$request->get('ward'))->first()->name;
            $add = $ward.", ".$district.", ".$province;

            $address = Address::findOrFail($id);
            $address->user_id = Auth::user()->id;
            $address->name = $request->get('name');
            $address->phone = $request->get('phone');
            $address->address = $add;
            $address->note = $request->get('note');
            $address->save();
            return back()->with('success','Thay đổi địa chỉ thành công');
        }
        return redirect()->route('index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/CheckcartController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\Checkcart;
use App\Models\Banner;
use App\Models\Product;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\User;
use App\Models\ProductCategory;
use App\Models\Post;
use Illuminate\Support\Facades\Auth;
use App\Models\Cart;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\FooterPost;
use App\Models\Tag;
class CheckcartController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $user=USer::all();
        $banner = Banner::all();
        $footerPost = FooterPost::where('status',1)->get();

        //hotTags in index
        $tags = Tag::all()->sortByDesc('views')->take(6);
        //hot tags in footer
        $tgs = Tag::all()->sortByDesc('views')->take(12);

        $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                    ->OrderBy('order','desc')
                                    ->get();

        $product = Product::where('status',1)->get();

        $posts = Post::where('status',1)->OrderBy('created_at','desc')->limit(5)->get();

        if(Auth::check()){
            $cartlist = Cart::where('user_id',Auth::user()->id)->count();
            $cart = Cart::where('user_id',Auth::user()->id)->get();
            return view('frontend.checkCart1', compact('tags','tgs','categories','product','banner','posts','cartlist','cart', 'user','footerPost'));
        }
        return view('frontend.checkCart1', compact('tags','tgs','categories','product','banner','posts','user','footerPost'));
    }
        
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        //
    }
    
    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    // public function store(Request $request)
    
    
    /**
    * Display the specified resource.
    *
    * @param  \App\Checkcart  $checkcart
    * @return \Illuminate\Http\Response
    */
    public function show(Request $request)
    {
        $footerPost = FooterPost::where('status',1)->get();

        //hotTags in index
        $tags = Tag::all()->sortByDesc('views')->take(6);
        //hot tags in footer
        $tgs = Tag::all()->sortByDesc('views')->take(12);
        
        //get all active categogies
        $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                        ->OrderBy('order','desc')->get();
        
        //get options
        $options = $request->get('option1');
        //seach by phone
        if($options == 0){

            $option =$request->get('data');
            $user=User::where('phone', $option)->get();

            if($user->isEmpty()){
                return back()->with('error','Số điện thoại sai hoặc chưa đăng kí tài khoản');
            }

            $order = Order::where('phone', $option)->get();
            $orderid = Order::select('id')->where('phone', $option)->get();
            
            if($order->isEmpty()){
                return back()->with('error','Chưa có đơn hàng nào trong giỏ hàng');
            }
            $orderid = $order->map->only(['id']);

            $productid = OrderDetail::where('orders_id', $orderid)->get();

            if(Auth::check()){
                $cartlist = Cart::where('user_id',Auth::user()->id)->count();
                $cart = Cart::where('user_id',Auth::user()->id)->get();
                return view('frontend.checkCart', compact('tags','tgs','categories','options','option','cartlist','cart', 'user', 'order', 'productid','footerPost'));
            }
            return view('frontend.checkCart', compact('tags','tgs','categories','options','option','user', 'order', 'productid','footerPost'));   
        }
        
        //search by email
        elseif($options == 1)
        {  
            $option = $request->get('data');

            $user = User::where('email', $option)->first();

            if($user === null){
                return back()->with('error', 'Email sai hoặc chưa đăng kí tài khoản');
            }

            $order = Order::where('user_id', $user->id)->get();

            if($order->isEmpty()){
                return back()->with('error','Chưa có đơn hàng nào trong giỏ hàng');
            }
            
            $orderid = $order->map->only(['id']);

            $productid = OrderDetail::where('orders_id', $orderid)->get();
            
            if(Auth::check()){

                $cartlist = Cart::where('user_id',Auth::user()->id)->count();
                $cart = Cart::where('user_id',Auth::user()->id)->get();
                return view('frontend.checkCart', compact('tags','categories','options','option','tgs','cartlist','cart', 'user', 'order', 'productid','footerPost'));
            }
            return view('frontend.checkCart', compact('tags','categories','tgs','options','option','user', 'order' , 'productid','footerPost')); 
        }
    }
    
    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Checkcart  $checkcart
    * @return \Illuminate\Http\Response
    */
    public function edit(Checkcart $checkcart)
    {
        //
    }
    
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Checkcart  $checkcart
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Checkcart $checkcart)
    {
        //
    }
    
    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Checkcart  $checkcart
    * @return \Illuminate\Http\Response
    */
    public function destroy(Checkcart $checkcart)
    {
        //
    }
}
    

app/Http/Controllers/Frontend/CodeController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Code;


class CodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/frontend/address.blade.php
@extends('layouts.frontend.app')
@section('content')
<div class="container">
    <div class="product pt-2 pb-lg-2">
        <!-- breadcum -->
        <div class="row"> 
            <ul class="breadcrumbs">
                <li class="nav-home">
                    <a href="#">
                        <a href="index.html"><i class="flaticon-home"></i></a>
                    </a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
                <li class="nav-item">
                    <a href="#">Thiết lập địa chỉ</a>
                </li>
                <li class="separator">
                    <i class="flaticon-right-arrow"></i>
                </li>
            </ul>
        </div>
        <!-- end breadcum -->
        
        {{-- avatar --}}
        @include('layouts.frontend.userInfoAva')
        {{-- end avatar --}}
        <div class="row">
            @include('layouts.frontend.userCategory')
            <div class="col-lg-9 col-12 mt-4">
                <div class="card">
                    <div class="row no-gutters">
                        <div class="pl-4 pt-4 col-lg-6 col-5">
                            <h3 style="border-left: 3px solid #f09819; padding-left:5px;"><b>Địa chỉ của tôi</b></h3>
                        </div>
                        <div class="col-7 col-lg-6 text-right pr-4" id="change_address">
                            <a href="{{url('tao-dia-chi')}}" class="mt-3 btn-gradient23 btn" style="width: 500x; margin-left:60px;"><i class="mr-1 fas fa-plus"></i>Thêm địa chỉ mới </a>
                        </div>
                        <hr width=100%>
                    </div>
                    @foreach ($address as $add)
                    <div class="row">
                        <div class="col-lg-9 col-10 pl-4">
                            <table class="table mt-3">
                                <thead>
                                    <tr>
                                        <th scope="col" style="width: 30%">Họ và tên</th>
                                        <th scope="col text-left">{{$add->name}}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Số điện thoại</td>
                                        <td class="text-leftt">{{$add->phone}}</td>
                                    </tr>
                                    <tr>
                                        <td>Địa chỉ</td>
                                        <td class="text-left">
                                            {{$add->note.', '.$add->address}}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-lg-3 col-2">
                            <div class="row edit pr-2">
                                <h4 class="pt-2 mr-lg-4 ml-2">
                                    <a href="{{route('manage-address.edit',$add->id)}}">Sửa</a>
                                </h4>
                                <form action="{{route('address.destroy',$add->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn-btn-delete">
                                        <i class="mr-1 fas fa-trash-alt"></i> Xóa
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <hr width=100%>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/frontend/tag.blade.php
@extends('layouts.frontend.app')
@section('content')
<div class="py-4 container">
    <div class="page-header">
        <div class="px-0 col-md-12">
            <div class="card-header" style="margin: 0px">
                <ul class="nav nav-pills nav-secondary" id="pills-tab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="pills-popular-tab" data-toggle="pill" href="#pills-popular" role="tab" aria-controls="pills-popular" aria-selected="true">{{$tag->name}}</a>
                    </li>
                </ul>
            </div>
            <div class="tab-content mt-2 mb-3" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-popular" role="tabpanel" aria-labelledby="pills-popular-tab">
                    {{-- products in tag --}}
                    <div class="row">
                        <div class="col-3">
                            <h2>Sản phẩm</h2>
                        </div>
                        <div class="col-9">
                            <div class="row">
                                @foreach ($product as $pro)
                                <div class="px-2 col-lg-3" >
                                    <div class="card-product">  
                                        <a href="{{route('san-pham.show',$pro->getProduct->slug)}}"> <img class="img-fluid" style="height: 210px;" src="{{asset('images/'.json_decode($pro->getProduct->filename)[0])}}" alt="Chania"></a>
                                        <div class="col">
                                            <div class="pt-3 title-card" style="height: 55px;">
                                                <a class="card-title" style="height: 50px;"  href="{{route('san-pham.show',$pro->getProduct->slug)}}">
                                                    <h4 class="ellipsis">
                                                        {{$pro->getProduct->name}} 
                                                    </h4>
                                                </a>
                                            </div>
                                            <div class="text-left common-cost" >
                                                <div class="col">
                                                    <div class="row">
                                                        @if (!empty($pro->getProduct->promotion))               
                                                        <p class="main-cost">
                                                            <b>{{number_format( $pro->getProduct->promotion*1000, 0, ',', '.' )}}đ</b>
                                                        </p>                
                                                        <p class="pt-1 abondon-text-cost">
                                                            {{number_format( $pro->getProduct->price*1000, 0, ',', '.' )}}đ
                                                        </p>
                                                        @else
                                                        <p class="main-cost">
                                                            <b>{{number_format( $pro->getProduct->price*1000, 0, ',', '.' )}}đ</b>
                                                        </p>
                                                        @endif
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            <div class="rating-star pb-2">
                                                <span class="fa fa-star checked" id="star"></span>
                                                <span class="fa fa-star checked" id="star"></span>
                                                <span class="fa fa-star checked" id="star"></span>
                                                <span class="fa fa-star" id="star"></span>
                                                <span class="fa fa-star" id="star"></span>
                                            </div>
                                            <div class="row pb-3 icon-view-details">
                                                <a href="{{route('san-pham.show',$pro->getProduct->slug)}}">
                                                    <div class="col" style="color: blue;">Xem chi tiết</div>
                                                </a>
                                                @if (Auth::check())
                                                <form action="{{route('cart.store')}}" method="post">
                                                    @csrf
                                                    <input type="text" value="{{Auth::user()->id}}" name="user_id" hidden>
                                                    <input type="text" value="1" name="quantity" hidden>
                                                    <input type="text" value="{{$pro->getProduct->id}}" name="product_id" hidden>
                                                    <input type="text" value="{{explode(',',$pro->getProduct->size)[0]}}" name="size" hidden>
                                                    <input type="text" value="{{explode(',',$pro->getProduct->color)[0]}}" name="color" hidden>
                                                    <button type="submit" class="btn-btn-cart">
                                                        <i class="fas fa-cart-plus" style="color: #f09819;"></i>
                                                    </button>
                                                </form>
                                                @else
                                                <a href="{{route('login')}}">
                                                    <div class="product-btn" style="color: #f09819;">
                                                        <i class="fas fa-cart-plus"></i>
                                                    </div>
                                                </a>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>

                            {{-- pagination --}}
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-4"></div>  
                                    <div class="col-4">
                                        {{ $product->appends(Illuminate\Support\Facades\Input::except('page')) }}
                                    </div>
                                    <div class="col-4"></div>
                                </div>
                            </div>
                            {{-- end pagination --}}
                        </div>
                    </div>
                    {{-- end products in tag --}}

                    {{-- posts in tag --}}
                    <div class="row">
                        <div class="col-3">
                            <h2>Bài viết</h2>
                        </div>
                        <div class="col-9">
                            <div class="row">
                                @foreach ($posts as $post)
                                <div class="px-2 col-lg-3" >
                                    <div class="item" id="title-post">
                                        <div class="img-blog">
                                            <a href="{{route('post.show',$post->getPost->slug)}}">
                                                <img src="{{asset('images/'.$post->getPost->filename)}}" style="height: 280px;" class="img-fluid pb-3" alt="...">
                                            </a>
                                        </div>
                                        <div class="col pt-2">
                                            <div class="title-post">
                                                <a href="{{route('post.show',$post->getPost->slug)}}"><h4>{{$post->getPost->title}}</h4></a>
                                            </div>
                                            <div class="time-post">
                                                <p class="date">{{$post->getPost->created_at}}</p>
                                                <p><i class="fas fa-comment mr-1"></i>Bình luận</p>
                                            </div>
                                            <p class="mb-1 description post-paragraph">{{$post->getPost->description}}</p>
                                            <a href="{{route('post.show',$post->getPost->slug)}}"><p>Đọc tiếp <i class="fas fa-arrow-circle-right"></i></p></a>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>

                            {{-- pagination --}}
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-4"></div>  
                                    <div class="col-4">
                                        {{ $posts->appends(Illuminate\Support\Facades\Input::except('page')) }}
                                    </div>
                                    <div class="col-4"></div>
                                </div>
                            </div>
                            {{-- end pagination --}}
                        </div>
                    </div>
                    {{-- end posts in tag --}}
                </div>
            </div>  
        </div>       
    </div> 
</div>
@endsection