routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//authentication
// Route::get('manage-product','Backend\ProductController@index');
Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logoutt');
Route::post('login', 'Auth\LoginController@authenticate')->name('loginn');

//socilite
//facebook
Route::get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderFacebookCallback');
//google
Route::get('login/google', 'Auth\LoginController@redirectToGoogleProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderGoogleCallback');

//backend

//filter
Route::get('manage-product/search','Backend\ProductController@filter')->name('filter');
Route::get('manage-quotation/search','Backend\QuotationController@filter')->name('qfilter');
Route::get('filter-orders', 'Backend\OrderController@filter')->name('filter-orders');
Route::get('manage-code/search', 'Backend\CodeController@filter')->name('filter-code');
Route::get('manage-post/search', 'Backend\PostController@filter')->name('filter-post');
Route::get('manage-promotion/search','Backend\PromotionController@filter')->name('filter-promotion');

Route::get('manage-comments', 'Backend\CommentController@post_comment')->name('manage-comments');
Route::get('filter-user', 'Backend\UserController@filter')->name('filter-user');
Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::resources([
    'manage-user' => 'Backend\UserController',
    'manage-product-category' => 'Backend\ProductCategoryController',
    'manage-product' => 'Backend\ProductController',
    'manage-post-category' => 'Backend\PostCategoryController',
    'manage-post' => 'Backend\PostController',
    'manage-tag' => 'Backend\TagController',
    'manage-banner' => 'Backend\BannerController',
    'manage-code' => 'Backend\CodeController',
    'manage-order' => 'Backend\OrderController',
    'manage-quotation' => 'Backend\QuotationController',
    'manage-footer-post' => 'Backend\FooterPostController',
    'manage-comment' => 'Backend\CommentController',
    'manage-file' => 'Backend\FileController',
    'manage-promotion'=> 'Backend\PromotionController'
]);


//frontend
// Route::get('search-product', 'Frontend\ProductController@search')->name('search_product');
Route::get('','Frontend\HomeController@index')->name('index');
Route::resource('index','Frontend\HomeController');
Route::resource('danh-muc','Frontend\ProductCategoryController');
Route::resource('post','Frontend\PostController');
Route::resource('san-pham','Frontend\ProductController');
Route::resource('cart','Backend\CartController');
Route::resource('order','Backend\OrderDetailController');
Route::resource('user','Frontend\UserController');
Route::resource('don-hang','Frontend\OrderController');
Route::resource('address','Backend\AddressController');
Route::resource('code','Frontend\CodeController');
Route::resource('manage-address','Frontend\AddressController');
Route::resource('footer-post','Frontend\FooterPostController');
Route::resource('tag','Frontend\TagController');
//quotation 
Route::resource('yeu-cau-bao-gia','Frontend\QuotationController');

Route::get('dia-chi','Backend\AddressController@create');
Route::get('tao-dia-chi','Backend\AddressController@createAddress');
Route::post('save-address','Backend\AddressController@storeAddressOnly');

Route::get('filter-order', 'Frontend\OrderController@filter')->name('filter-order');
Route::get('filter-product-cate/{id}', 'Frontend\ProductCategoryController@filter')->name('filter-product-cate');
Route::get('search', 'Frontend\HomeController@search')->name('search-product');
Route::post('filter-search', 'Frontend\HomeController@filterSearch')->name('filter-search');

//comments for post
Route::post('comments', 'Frontend\CommentController@store')->name('comment');

Route::post('comment-product', 'Frontend\CommentController@product')->name('comment-product');

Route::get('check-cart', 'Frontend\CheckcartController@index')->name('check-cart');
Route::get('list-cart', 'Frontend\CheckcartController@show')->name('list-cart');

Route::post('reply', 'Frontend\ReplyController@store')->name('reply');

Route::post('saving-data','Backend\AddressController@store');
Route::post('saving-order','Backend\AddressController@save');
Route::get('thanh-toan','Backend\AddressController@index');
Route::get('get-district-list','Backend\AddressController@getDistrictList');
Route::get('get-ward-list','Backend\AddressController@getWardList');



//change user password by themselve
Route::post('update-password','Frontend\UserController@updatePassword')->name('update-password');

//export data user 
Route::get('export', 'Backend\ExportController@export')->name('export');
Route::get('export-order', 'Backend\ExportOrderController@export')->name('export-order');
Route::get('export-product', 'Backend\ExportProductController@export')->name('export-product');
Route::get('export-code', 'Backend\ExportCodeController@export')->name('export-code');

app/Http/Controllers/Backend/AddressController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Address;
use App\Models\OrderDetail;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Models\Cart;
use App\Models\Code;
use App\Models\Province;
use App\Models\District;
use App\Models\Order;
use App\Models\Ward;
use Illuminate\Support\Facades\Mail;
use App\Mail\MailNotify;
use App\Models\FooterPost;
use App\Models\Tag;
use App\Models\ProductCategory;


class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(!Auth::check())
        {
            return redirect()->route('login');
        }
        //hotTags in index
        $tags = Tag::all()->sortByDesc('views')->take(6);
        //hot tags in footer
        $tgs = Tag::all()->sortByDesc('views')->take(12);

        //get all active categogies
        $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                    ->OrderBy('order','desc')->get();

        $cartlist = Cart::where('user_id',Auth::user()->id)->count();

        $cart = Cart::where('user_id',Auth::user()->id)->get();
        if(!($cart->count() > 0))
        {
            return back()->with('error','Không có sản phẩm nào trong giỏ hàng');
        }
        foreach($cart as $ct)
        {
            if($ct->proInCart->quantity < $ct->quantity)
            {
                return back()->with('error',"<b>{$ct->proInCart->name}</b> <br> không đủ trong kho, vui lòng thay đổi số lượng hoặc xóa sản phẩm");
            }
        }

        $user = User::where('id',Auth::user()->id)->first();

        $code = Code::where('code',$request->get('voucher'))->first();

        $footerPost = FooterPost::where('status',1)->get();

        $provinces = Province::pluck("name","id");

        $sum = 0;
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        
        return view('frontend.payment',compact('tags','tgs','categories','provinces','user','cartlist','cart','sum','footerPost'));
    }

    public function getDistrictList(Request $request)
    {
        $districts = District::where("province_id",$request->province_id)->pluck("name","id");
        return response()->json($districts);
    }

    public function getWardList(Request $request)
    {
        $wards = Ward::where("district_id",$request->district_id)->pluck("name","id");
        return response()->json($wards);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::check())
        {   
            $footerPost = FooterPost::where('status',1)->get();
            $address = Address::where('user_id',Auth::user()->id)->get();

            //hotTags in index
            $tags = Tag::all()->sortByDesc('views')->take(6);
            //hot tags in footer
            $tgs = Tag::all()->sortByDesc('views')->take(12);

            //get all active categogies
            $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                        ->OrderBy('order','desc')->get();
                                    
            $cartlist = Cart::where('user_id',Auth::user()->id)->count();
            $cart = Cart::where('user_id',Auth::user()->id)->get();
            return view ('frontend.address',compact('tags','tgs','categories','cart','cartlist','address','footerPost'));
        }
        return redirect()->route('login');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    //store order when users haven't had address yet
    public function store(Request $request)
    {
        //hotTags in index
        $tags = Tag::all()->sortByDesc('views')->take(6);
        //hot tags in footer
        $tgs = Tag::all()->sortByDesc('views')->take(12);

        //get all active categogies
        $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                    ->OrderBy('order','desc')->get();
                                    
        $cartlist = Cart::where('user_id',Auth::user()->id)->count();
        $cart = Cart::where('user_id',Auth::user()->id)->get();

        $user = User::where('id',Auth::user()->id)->first();

        $code = Code::where('code',$request->get('voucher'))->first();

        $footerPost = FooterPost::where('status',1)->get();

        $provinces = Province::pluck("name","id");

        $sum = 0;
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        switch($request->input('action'))
        {
            case 'voucher':
                {
                    
                    $name = $request->get('name');
                    $note = $request->get('note');
                    
                    $phone = $request->get('phone');
                    $code = Code::where('code',$request->get('voucher'))->first();

                    //get address
                    $province = Province::where('id',$request->get('province'))->first();
                    $district = District::where('id',$request->get('district'))->first();
                    $ward = Ward::where('id',$request->get('ward'))->first();

                    //get payment method
                    $method = $request->get('method');

                    if(!empty($code))
                    {
                        $checkCode = Order::where([['user_id',Auth::user()->id],
                                                ['voucher','like',"$code->code%"]])->first();

                        //validate voucher
                        if($checkCode)
                        {
                            return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                            'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                            'footerPost','provinces','categories'),
                                    ['error'=>'Bạn đã sử dụng mã giảm giá']);

                        }elseif($code->use_time == 0)
                        {
                            return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                            'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                            'footerPost','provinces','categories'),
                                    ['error'=>'Mã giảm giá đã hết lượt dùng']);

                        }elseif(date('Y-m-d',strtotime(str_replace('/','-',$code->end_time))) < date("Y-m-d"))
                        {
                            return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                            'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                            'footerPost','provinces','categories'),
                                    ['error'=>'Mã giảm giá đã hết hạn sử dụng']);
                            
                        }elseif($code->limited > $request->get('price'))
                        {
                            return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                            'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                            'footerPost','provinces','categories'),
                                    ['error'=>'Giá trị đơn hàng chưa đủ để sử dụng mã giảm giá này']);
                        }

                        return view('frontend.payment',compact('categories','code','method','province','district','ward','name','note','tags','tgs','phone','sum','cartlist','cart','user','footerPost','provinces'));
                    }else
                    {
                        return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                        'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                        'footerPost','provinces','categories'),
                                                        ['error'=>'Mã giảm giá không tồn tại']);
                    }
                break;
                }
            case 'paymoney':
                {
                    //validate
                    $request->validate([
                        'phone' => ['regex:/(01[2|6|8|9]|03[2|3|4|5|6|7|8|9]|05[6|8|9]|08[1|2|3|4|5|6|9|8]|09[0|1|2|3|4|2|6|7|8|9])+([0-9]{7})\b/']
                    ]);
                    
                    //create address
                    if($request->get('provincess') != null && $request->get('districtt') != null && $request->get('wardd') != null)
                    {
                        $province = Province::where('id',(int)$request->get('provincess'))->first()->name;
                        $district = District::where('id',(int)$request->get('districtt'))->first()->name;
                        $ward = Ward::where('id',(int)$request->wardd)->first()->name;
                        $add = $ward.", ".$district.", ".$province;
                    }
                    else if($request->get('province') != null && $request->get('district') != null && $request->get('ward') != null) 

app/Http/Controllers/Backend/DistrictController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\District;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class DistrictController extends Controller
{
    public function showDistrictInProvince(Request $request)
	{
		if ($request->ajax()) {
			$districts = District::where('province_id',$request->province_id)->select('id', 'name')->get();

			return response()->json($districts);
		}
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function show(District $district)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function edit(District $district)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, District $district)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function destroy(District $district)
    {
        //
    }
}

resources/views/layouts/backend/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    @include('layouts.backend.head')
</head>
<body>
    <div class="wrapper">
        @include('layouts.backend.logo-navbar')
        @include('layouts.backend.sidebar')
        <div class="main-panel">
            <div class="content">
                <div class="page-inner">
                    <div class="page-header">
                        <h4 class="page-title">
                            {{ request()->is('manage-user') ? 'Quản lý người dùng' : '' }}
                            {{ request()->is('manage-post') ? 'Quản lý bài viết' : '' }}
                            {{ request()->is('manage-post-category') ? 'Quản lý danh mục bài viết' : '' }}
                            {{ request()->is('manage-tag') ? 'Quản lý tag' : '' }}
                            {{ request()->is('manage-product') ? 'Quản lý sản phẩm' : '' }}
                            {{ request()->is('manage-product-category') ? 'Quản lý danh mục sản phẩm' : '' }}
                            {{ request()->is('manage-code') ? 'Quản lý mã giảm giá' : '' }}
                        </h4>
                    </div>
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @include('layouts.backend.script')
    @yield('script')
</body>
</html>

resources/views/layouts/backend/logo-navbar.blade.php
<div class="main-header" data-background-color="purple">
    <!-- Logo Header -->
    <div class="logo-header">
        
        <a href="{{route('index')}}" class="logo">
            <img src="{{asset('images/logo_without_text.png')}}" alt="navbar brand" class="navbar-brand" style="width: 75px;">
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class="fa fa-bars"></i>
            </span>
        </button>
        <button class="topbar-toggler more"><i class="fa fa-ellipsis-v"></i></button>
        <div class="navbar-minimize">
            <button class="btn btn-minimize btn-rounded">
                <i class="fa fa-bars"></i>
            </button>
        </div>
    </div>
    <!-- End Logo Header -->
    
    <!-- Navbar Header -->
    <nav class="navbar navbar-header navbar-expand-lg">
        
        <div class="container-fluid">
            <div class="collapse" id="search-nav">
            </div>
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                <li class="nav-item dropdown hidden-caret">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                        <div class="avatar-sm">
                            @if (Auth::user()->avatar)
                                <img src="{{asset('profile/'.Auth::user()->avatar)}}" alt="image profile" class="avatar-img rounded-circle">
                            @else
                                <img src="{{asset('profile/default_av.png')}}" alt="image profile" class="avatar-img rounded-circle">
                            @endif
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-user animated fadeIn">
                        <li>
                            <div class="user-box">
                                <div class="avatar-lg">
                                    @if (Auth::user()->avatar)
                                        <img src="{{asset('profile/'.Auth::user()->avatar)}}" alt="image profile" class="avatar-img rounded">
                                    @else
                                        <img src="{{asset('profile/default_av.png')}}" alt="image profile" class="avatar-img rounded">
                                    @endif
                                    
                                </div>
                                <div class="u-text">
                                    <h4>{{ Auth::user()->username }}</h4>
                                    <p class="text-muted">{{ Auth::user()->email }}</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{route('user.show',Auth::user()->id)}}">Trang cá nhân</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{route('index')}}">Trang chủ</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('logoutt') }}">
                                Logout
                            </a>
                        </li>
                    </ul>
                </li>
                
            </ul>
        </div>
    </nav>
    <!-- End Navbar -->
</div>

resources/views/layouts/backend/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-background"></div>
    <div class="sidebar-wrapper scrollbar-inner">
        <div class="sidebar-content">
            <div class="user">
                <div class="avatar-sm float-left mr-2">
                    @if (Auth::user()->avatar)
                        <img src="{{asset('profile/'.Auth::user()->avatar)}}" alt="image profile" class="avatar-img rounded-circle">
                    @else
                        <img src="{{asset('profile/default_av.png')}}" alt="image profile" class="avatar-img rounded-circle">
                    @endif
                </div>
                <div class="info">
                    <a data-toggle="collapse" href="#collapseExample" aria-expanded="true">
                        <span>
                            {{ Auth::user()->username }}
                            <span class="user-level">Administrator</span>
                            <span class="caret"></span>
                        </span>
                    </a>
                    <div class="clearfix"></div>
                    
                    <div class="collapse in" id="collapseExample">
                        <ul class="nav">
                            <li>
                                <a href="#profile">
                                    <span class="link-collapse">My Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="#edit">
                                    <span class="link-collapse">Edit Profile</span>
                                </a>
                            </li>
                            <li>
                                <a href="#settings">
                                    <span class="link-collapse">Settings</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <ul class="nav">
                <li class="nav-item">
                    <a href="{{route('home')}}">
                        <i class="fas fa-home"></i>
                        <p>Dashboard</p>
                        <span class="badge badge-count">5</span>
                    </a>
                </li>
                <li class="nav-item {{ request()->is('manage-user') ? 'active' : '' }}">
                    <a href="{{route('manage-user.index')}}">
                        <i class="fas fa-address-card"></i>
                        <p>Người dùng</p>
                    </a>
                </li>
                <li class="nav-item {{ (request()->is('manage-order') || request()->is('manage-order/*')) ? 'active' : '' }}">
                    <a href="{{route('manage-order.index')}}">
                        <i class="fas fa-shopping-cart"></i>
                        <p>Đơn hàng</p>
                    </a>
                </li>
                <li class="nav-item {{ (request()->is('manage-product') || request()->is('manage-product/*') ||
                        request()->is('manage-product-category') || request()->is('manage-product-category/*') ||
                        request()->is('manage-quotation') || request()->is('manage-quotation/*') ||
                        request()->is('manage-code') || request()->is('manage-code/*')) ? 'active' : '' }}">
                    <a href="#product" data-toggle="collapse">
                        <i class="fas fa-tshirt"></i>
                        <p>Sản phẩm</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse {{ (request()->is('manage-product') || request()->is('manage-product/*') ||
                    request()->is('manage-product-category') || request()->is('manage-product-category/*') ||
                    request()->is('manage-quotation') || request()->is('manage-quotation/*') ||
                    request()->is('manage-code') || request()->is('manage-code/*')) ? 'show' : '' }}" id="product">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{{route('manage-product-category.index')}}">
                                    <span class="sub-item">Danh mục sản phẩm</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{route('manage-product.index')}}">
                                    <span class="sub-item">Sản phẩm</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{route('manage-code.index')}}">
                                    <span class="sub-item">Mã giảm giá</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{route('manage-quotation.index')}}">
                                    <span class="sub-item">Yêu cầu báo giá</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item {{ (request()->is('manage-post') || request()->is('manage-post/*') ||
                request()->is('manage-post-category') || request()->is('manage-post-category/*') ||
                request()->is('manage-footer-post') || request()->is('manage-footer-post/*')) ? 'active' : '' }}">
                    <a href="#post" data-toggle="collapse">
                        <i class="fas fa-newspaper"></i>
                        <p>Bài viết</p>
                        <span class="caret"></span>
                    </a>
                    <div class="collapse {{ (request()->is('manage-post') || request()->is('manage-post/*') ||
                        request()->is('manage-post-category') || request()->is('manage-post-category/*') ||
                        request()->is('manage-footer-post') || request()->is('manage-footer-post/*')) ? 'show' : '' }}" id="post">
                        <ul class="nav nav-collapse">
                            <li>
                                <a href="{{route('manage-post-category.index')}}">
                                    <span class="sub-item">Danh mục bài viết</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{route('manage-post.index')}}">
                                    <span class="sub-item">Bài viết thương mại</span>
                                </a>
                            </li>
                            <li>
                                <a href="{{route('manage-footer-post.index')}}">
                                    <span class="sub-item">Bài viết giới thiệu</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item {{ request()->is('manage-tag') ? 'active' : '' }}">
                    <a href="{{route('manage-tag.index')}}">
                        <i class="fas fa-hashtag"></i>
                        <p>Tag</p>
                    </a>
                </li>
                <li class="nav-item {{ request()->is('manage-banner')|| request()->is('manage-banner/*') ? 'active' : '' }}">
                    <a href="{{route('manage-banner.index')}}">
                        <i class="fas fa-file-image"></i>
                        <p>Banner</p>
                    </a>
                </li>
                <li class="nav-item {{ request()->is('manage-comment') || request()->is('manage-comment/*') ? 'active' : '' }}">
                    <a href="{{route('manage-comment.index')}}">
                        <i class="fas fa-file-image"></i>
                        <p>Nhận xét sản phẩm</p>
                    </a>
                </li>
                <li class="nav-item {{ request()->is('manage-comments') || request()->is('manage-comments/*') ? 'active' : '' }}">
                    <a href="{{route('manage-comments')}}">
                        <i class="fas fa-file-image"></i>
                        <p>Nhận xét bài viết</p>
                    </a>
                </li>
                <li class="nav-item {{ request()->is('manage-promotion') ? 'active' : '' }}">
                    <a href="{{route('manage-promotion.index')}}">
                        <i class="fas fa-file-image"></i>
                        <p>Gửi mail khuyến mại</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>