routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//authentication
// Route::get('manage-product','Backend\ProductController@index');
Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logoutt');
Route::post('login', 'Auth\LoginController@authenticate')->name('loginn');

//socilite
//facebook
Route::get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderFacebookCallback');
//google
Route::get('login/google', 'Auth\LoginController@redirectToGoogleProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderGoogleCallback');

//backend

//filter
Route::get('manage-product/search','Backend\ProductController@filter')->name('filter');
Route::get('manage-quotation/search','Backend\QuotationController@filter')->name('qfilter');
Route::get('filter-orders', 'Backend\OrderController@filter')->name('filter-orders');
Route::get('manage-code/search', 'Backend\CodeController@filter')->name('filter-code');
Route::get('manage-post/search', 'Backend\PostController@filter')->name('filter-post');
Route::get('manage-promotion/search','Backend\PromotionController@filter')->name('filter-promotion');

Route::get('manage-comments', 'Backend\CommentController@post_comment')->name('manage-comments');
Route::get('filter-user', 'Backend\UserController@filter')->name('filter-user');
Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::resources([
    'manage-user' => 'Backend\UserController',
    'manage-product-category' => 'Backend\ProductCategoryController',
    'manage-product' => 'Backend\ProductController',
    'manage-post-category' => 'Backend\PostCategoryController',
    'manage-post' => 'Backend\PostController',
    'manage-tag' => 'Backend\TagController',
    'manage-banner' => 'Backend\BannerController',
    'manage-code' => 'Backend\CodeController',
    'manage-order' => 'Backend\OrderController',
    'manage-quotation' => 'Backend\QuotationController',
    'manage-footer-post' => 'Backend\FooterPostController',
    'manage-comment' => 'Backend\CommentController',
    'manage-file' => 'Backend\FileController',
    'manage-promotion'=> 'Backend\PromotionController'
]);


//frontend
// Route::get('search-product', 'Frontend\ProductController@search')->name('search_product');
Route::get('','Frontend\HomeController@index')->name('index');
Route::resource('index','Frontend\HomeController');
Route::resource('danh-muc','Frontend\ProductCategoryController');
Route::resource('post','Frontend\PostController');
Route::resource('san-pham','Frontend\ProductController');
Route::resource('cart','Backend\CartController');
Route::resource('order','Backend\OrderDetailController');
Route::resource('user','Frontend\UserController');
Route::resource('don-hang','Frontend\OrderController');
Route::resource('address','Backend\AddressController');
Route::resource('code','Frontend\CodeController');
Route::resource('manage-address','Frontend\AddressController');
Route::resource('footer-post','Frontend\FooterPostController');
Route::resource('tag','Frontend\TagController');
//quotation 
Route::resource('yeu-cau-bao-gia','Frontend\QuotationController');

Route::get('dia-chi','Backend\AddressController@create');
Route::get('tao-dia-chi','Backend\AddressController@createAddress');
Route::post('save-address','Backend\AddressController@storeAddressOnly');

Route::get('filter-order', 'Frontend\OrderController@filter')->name('filter-order');
Route::get('filter-product-cate/{id}', 'Frontend\ProductCategoryController@filter')->name('filter-product-cate');
Route::get('search', 'Frontend\HomeController@search')->name('search-product');
Route::post('filter-search', 'Frontend\HomeController@filterSearch')->name('filter-search');

//comments for post
Route::post('comments', 'Frontend\CommentController@store')->name('comment');

Route::post('comment-product', 'Frontend\CommentController@product')->name('comment-product');

Route::get('check-cart', 'Frontend\CheckcartController@index')->name('check-cart');
Route::get('list-cart', 'Frontend\CheckcartController@show')->name('list-cart');

Route::post('reply', 'Frontend\ReplyController@store')->name('reply');

Route::post('saving-data','Backend\AddressController@store');
Route::post('saving-order','Backend\AddressController@save');
Route::get('thanh-toan','Backend\AddressController@index');
Route::get('get-district-list','Backend\AddressController@getDistrictList');
Route::get('get-ward-list','Backend\AddressController@getWardList');



//change user password by themselve
Route::post('update-password','Frontend\UserController@updatePassword')->name('update-password');

//export data user 
Route::get('export', 'Backend\ExportController@export')->name('export');
Route::get('export-order', 'Backend\ExportOrderController@export')->name('export-order');
Route::get('export-product', 'Backend\ExportProductController@export')->name('export-product');
Route::get('export-code', 'Backend\ExportCodeController@export')->name('export-code');

app/Http/Controllers/Backend/AddressController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Address;
use App\Models\OrderDetail;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use App\Models\Cart;
use App\Models\Code;
use App\Models\Province;
use App\Models\District;
use App\Models\Order;
use App\Models\Ward;
use Illuminate\Support\Facades\Mail;
use App\Mail\MailNotify;
use App\Models\FooterPost;
use App\Models\Tag;
use App\Models\ProductCategory;


class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(!Auth::check())
        {
            return redirect()->route('login');
        }
        //hotTags in index
        $tags = Tag::all()->sortByDesc('views')->take(6);
        //hot tags in footer
        $tgs = Tag::all()->sortByDesc('views')->take(12);

        //get all active categogies
        $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                    ->OrderBy('order','desc')->get();

        $cartlist = Cart::where('user_id',Auth::user()->id)->count();

        $cart = Cart::where('user_id',Auth::user()->id)->get();
        if(!($cart->count() > 0))
        {
            return back()->with('error','Không có sản phẩm nào trong giỏ hàng');
        }
        foreach($cart as $ct)
        {
            if($ct->proInCart->quantity < $ct->quantity)
            {
                return back()->with('error',"<b>{$ct->proInCart->name}</b> <br> không đủ trong kho, vui lòng thay đổi số lượng hoặc xóa sản phẩm");
            }
        }

        $user = User::where('id',Auth::user()->id)->first();

        $code = Code::where('code',$request->get('voucher'))->first();

        $footerPost = FooterPost::where('status',1)->get();

        $provinces = Province::pluck("name","id");

        $sum = 0;
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        
        return view('frontend.payment',compact('tags','tgs','categories','provinces','user','cartlist','cart','sum','footerPost'));
    }

    public function getDistrictList(Request $request)
    {
        $districts = District::where("province_id",$request->province_id)->pluck("name","id");
        return response()->json($districts);
    }

    public function getWardList(Request $request)
    {
        $wards = Ward::where("district_id",$request->district_id)->pluck("name","id");
        return response()->json($wards);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::check())
        {   
            $footerPost = FooterPost::where('status',1)->get();
            $address = Address::where('user_id',Auth::user()->id)->get();

            //hotTags in index
            $tags = Tag::all()->sortByDesc('views')->take(6);
            //hot tags in footer
            $tgs = Tag::all()->sortByDesc('views')->take(12);

            //get all active categogies
            $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                        ->OrderBy('order','desc')->get();
                                    
            $cartlist = Cart::where('user_id',Auth::user()->id)->count();
            $cart = Cart::where('user_id',Auth::user()->id)->get();
            return view ('frontend.address',compact('tags','tgs','categories','cart','cartlist','address','footerPost'));
        }
        return redirect()->route('login');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    //store order when users haven't had address yet
    public function store(Request $request)
    {
        //hotTags in index
        $tags = Tag::all()->sortByDesc('views')->take(6);
        //hot tags in footer
        $tgs = Tag::all()->sortByDesc('views')->take(12);

        //get all active categogies
        $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                    ->OrderBy('order','desc')->get();
                                    
        $cartlist = Cart::where('user_id',Auth::user()->id)->count();
        $cart = Cart::where('user_id',Auth::user()->id)->get();

        $user = User::where('id',Auth::user()->id)->first();

        $code = Code::where('code',$request->get('voucher'))->first();

        $footerPost = FooterPost::where('status',1)->get();

        $provinces = Province::pluck("name","id");

        $sum = 0;
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        switch($request->input('action'))
        {
            case 'voucher':
                {
                    
                    $name = $request->get('name');
                    $note = $request->get('note');
                    
                    $phone = $request->get('phone');
                    $code = Code::where('code',$request->get('voucher'))->first();

                    //get address
                    $province = Province::where('id',$request->get('province'))->first();
                    $district = District::where('id',$request->get('district'))->first();
                    $ward = Ward::where('id',$request->get('ward'))->first();

                    //get payment method
                    $method = $request->get('method');

                    if(!empty($code))
                    {
                        $checkCode = Order::where([['user_id',Auth::user()->id],
                                                ['voucher','like',"$code->code%"]])->first();

                        //validate voucher
                        if($checkCode)
                        {
                            return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                            'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                            'footerPost','provinces','categories'),
                                    ['error'=>'Bạn đã sử dụng mã giảm giá']);

                        }elseif($code->use_time == 0)
                        {
                            return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                            'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                            'footerPost','provinces','categories'),
                                    ['error'=>'Mã giảm giá đã hết lượt dùng']);

                        }elseif(date('Y-m-d',strtotime(str_replace('/','-',$code->end_time))) < date("Y-m-d"))
                        {
                            return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                            'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                            'footerPost','provinces','categories'),
                                    ['error'=>'Mã giảm giá đã hết hạn sử dụng']);
                            
                        }elseif($code->limited > $request->get('price'))
                        {
                            return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                            'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                            'footerPost','provinces','categories'),
                                    ['error'=>'Giá trị đơn hàng chưa đủ để sử dụng mã giảm giá này']);
                        }

                        return view('frontend.payment',compact('categories','code','method','province','district','ward','name','note','tags','tgs','phone','sum','cartlist','cart','user','footerPost','provinces'));
                    }else
                    {
                        return view('frontend.payment',compact('code','method','province','district','ward','name',
                                                        'note','tags','tgs','phone','sum','cartlist','cart','user',
                                                        'footerPost','provinces','categories'),
                                                        ['error'=>'Mã giảm giá không tồn tại']);
                    }
                break;
                }
            case 'paymoney':
                {
                    //validate
                    $request->validate([
                        'phone' => ['regex:/(01[2|6|8|9]|03[2|3|4|5|6|7|8|9]|05[6|8|9]|08[1|2|3|4|5|6|9|8]|09[0|1|2|3|4|2|6|7|8|9])+([0-9]{7})\b/']
                    ]);
                    
                    //create address
                    if($request->get('provincess') != null && $request->get('districtt') != null && $request->get('wardd') != null)
                    {
                        $province = Province::where('id',(int)$request->get('provincess'))->first()->name;
                        $district = District::where('id',(int)$request->get('districtt'))->first()->name;
                        $ward = Ward::where('id',(int)$request->wardd)->first()->name;
                        $add = $ward.", ".$district.", ".$province;
                    }
                    else if($request->get('province') != null && $request->get('district') != null && $request->get('ward') != null) 

app/Http/Controllers/Backend/DistrictController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\District;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class DistrictController extends Controller
{
    public function showDistrictInProvince(Request $request)
	{
		if ($request->ajax()) {
			$districts = District::where('province_id',$request->province_id)->select('id', 'name')->get();

			return response()->json($districts);
		}
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function show(District $district)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function edit(District $district)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, District $district)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function destroy(District $district)
    {
        //
    }
}

resources/views/backend/editCode.blade.php
@extends('layouts.backend.app')
@section('content')
<div class="card-header">
    <h3>Chỉnh sửa thông tin code</h3>
</div>

<form action="{{route('manage-code.update', $code->id)}}" method="POST">
    @method('PATCH')
    @csrf
    <div class="card-body">
        <label><strong>Mã giảm giá</strong></label>
        <input type="text" name="code" class="form-control" value="{{$code->code}}" readonly>
        <br>

        <label><strong>Chức năng</strong></label>
        <br>
        @if ($code->role == 0)
        Giảm theo % <input type="radio" name="role" id="" value="0" checked="checked"> &nbsp; &nbsp;
        Giảm theo tiền mặt (nghìn đồng)<input type="radio" name="role" id="" value="1">
        <br>
        @else
        Giảm theo % <input type="radio" name="role" id="" value="0" > &nbsp; &nbsp;
        Giảm theo tiền mặt (nghìn đồng) <input type="radio" name="role" id="" value="1" checked="checked">
        @endif
        <br>
        <br>
        <label><strong>Đơn vị giảm</strong></label>
        <input type="text" name="amount" class="form-control" value="{{$code->amount}}">
        <br>
        <br>
        <label><strong>Áp dụng cho đơn hàng từ: (.000 VNĐ)</strong></label>
        <input type="text" name="limited" class="form-control" value="{{$code->limited}}">
        <br>
        <label><strong>Số lượt dùng</strong></label>
        <input type="text" name="use_time" class="form-control" value="{{$code->use_time}}" >
        <br>
    </div>
    <div class="card-footer">
        <a href="" class="btn btn-danger">Hủy</a>
        <button type="submit" class="btn btn-primary">Lưu thay đổi</button>
    </div>
</form>
@endsection

resources/views/backend/footerPost.blade.php
@extends('layouts.backend.app')
@section('content')
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">Danh sách bài viết giới thiệu</h4>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <div class="row">
                    <div class="col-6">
                        <a href="{{route('manage-footer-post.create')}}" class="btn btn-primary">
                            <span class="btn-label">
                                <i class="fa fa-plus"></i>
                            </span>
                            Thêm bài viết
                        </a>
                    </div>
                    <div class="col-12">
                        <hr>
                    </div>
                </div>
                <table id="basic-datatables" class="display table table-striped table-hover">
                    <!-- Example single danger button -->
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên bài viết</th>
                            <th>Danh mục</th>
                            <th>Trạng thái</th>
                            <th>Ngày đăng</th>
                            <th>Hành động</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>STT</th>
                            <th>Tên bài viết</th>
                            <th>Danh mục</th>
                            <th>Trạng thái</th>
                            <th>Ngày đăng</th>
                            <th>Hành động</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($post as $ps)
                        <tr>
                            <td>
                                {{$i++}}
                            </td>
                            <td width="25%">
                                <a href="{{route('footer-post.show',$ps->slug)}}" target="_blank" rel="noopener noreferrer">{{$ps->title}}</a>
                            </td>
                            <td>
                                @if ($ps->category == 0)
                                    Hỗ trợ
                                @elseif($ps->category == 1)
                                    Liên hệ
                                @elseif($ps->category == 2)
                                    Hotline
                                @elseif($ps->category == 3)
                                    Email
                                @elseif($ps->category == 4)
                                    Câu hỏi thường gặp
                                @elseif($ps->category == 5)
                                    Thông báo
                                @elseif($ps->category == 6)
                                    Chi tiết sản phẩm
                                @elseif($ps->category == 7)
                                    Thông tin trang web
                                @endif
                            </td>
                            <td>
                                @if ($ps->status == 1)
                                Hoạt động
                                @else
                                tạm ẩn
                                @endif
                            </td>
                            <td>
                                {{$ps->created_at}}
                            </td>
                            <td class="mt-2 navbar-nav text-center">
                                <li class="nav-item dropdown hidden-caret">
                                    <a class="dropdown-toggle profile-pic mt-1" data-toggle="dropdown" href="#" aria-expanded="false">
                                        Thao tác
                                    </a>
                                    <ul class="dropdown-menu dropdown-user animated fadeIn" style="width:10%">
                                        <li>
                                            <div>
                                                <a class="dropdown-item btn-primary text-center btn-link" href="{{route('manage-footer-post.show', $ps->id)}}" data-toggle="tooltip" data-placement="bottom"  title="View">
                                                    <i class="fas fa-eye"></i>
                                                </a>
                                            </div>
                                            <div>
                                                <a class="dropdown-item btn-secondary text-center btn-link" href="{{route('manage-footer-post.edit', $ps->id)}}" data-toggle="tooltip" data-placement="bottom" title="Edit">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                            </div>
                                            <div>
                                                <form action="{{ route('manage-footer-post.destroy', $ps->id)}}" method="post">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit" class="dropdown-item btn-danger text-center btn-link" data-toggle="tooltip" data-placement="bottom" title="Delete">
                                                        <i class="fas fa-trash"></i>  
                                                    </button>
                                                </form>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            </td>
                        </tr>
                        @endforeach 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
    //== Class definition
    var SweetAlert2Demo = function() {
        //== Demos
        var initDemos = function() {
            $('.btn-danger').click(function(e) {
                var $form =  $(this).closest("form");
                e.preventDefault();
                swal({
                    title: 'Bạn có chắc muốn xóa bài viết này?',
                    text: "Một khi đã xóa sẽ không thể khôi phục!",
                    type: 'warning',
                    buttons:{
                        confirm: {
                            text : 'Có, Xóa đi!',
                            className : 'btn btn-success'
                        },
                        cancel: {
                            visible: true,
                            text: 'Hủy',
                            className: 'btn btn-danger'
                        }
                    }
                }).then((Delete) => {
                    
                    if (Delete) {
                        if (Delete) {
                            $form.submit();
                        }
                        swal({
                            title: user_id,
                            text: 'Your file has been deleted.',
                            type: 'success',
                            buttons : {
                                confirm: {
                                    className : 'btn btn-success'
                                }
                            }
                        });
                    } else {
                        swal.close();
                    }
                });
            });
        };
        return {
            //== Init
            init: function() {
                initDemos();
            },
        };
    }();
    
    //== Class Initialization
    jQuery(document).ready(function() {
        SweetAlert2Demo.init();
    });
</script>
@endsection

resources/views/backend/showOrder.blade.php
@extends('layouts.backend.app')
@section('content')
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-6">
                <h3>Thông tin đơn hàng {{$order->order_code}}</h3>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        <label>Mã đơn hàng </label>
        <input type="text" class="form-control" value="{{$order->order_code}}" readonly>
        <br>
        <label><strong>Địa chỉ nhận hàng</strong></label>
        <input type="text" class="form-control" value="{{$order->address}}" readonly>
        <br>
        <label><strong>Người nhận</strong></label>
        <input type="text" class="form-control" value="{{$order->name}}" readonly>
        <br>
        <label><strong>Số điện thoại người nhận</strong></label>
        <input type="text" class="form-control" value="{{$order->phone}}" readonly>
        <br>
        <label><strong>Các loại hàng order</strong></label>
        <table class="table table-bodered">
            <thead>
                <th>Tên sản phẩm</th>
                <th>Ảnh sản phẩm</th>
                <th>Thuộc tính</th>
                <th>Số lượng</th>
                <th>Thành tiền</th>
            </thead>
            <tbody>
                @foreach ($order->orderDetail as $item)
                <tr>
                    <td width="25%">
                        <a href="{{route('san-pham.show',$item->productOrder->slug)}}">{{$item->productOrder->name}}</a>
                    </td>
                    <td>
                        <img src="{{asset('images/'.json_decode($item->productOrder->filename)[0])}}"  class="img-fluid" alt="..." width="60px" height="60px;">
                    </td>
                    <td>
                        Màu sắc: {{$item->color}} <br>
                        Kích cỡ: {{$item->size}}
                    </td>
                    <td>{{$item->quantity}}</td>
                    <td>
                        @if ($item->productOrder->promotion)
                        {{number_format($item->productOrder->promotion*$item->quantity, 0, ',', ' ' ).'.000đ'}}
                        @else
                        {{number_format($item->productOrder->price*$item->quantity, 0, ',', ' ' ).'.000đ'}}
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <br>
        <label><strong>Phương thức thanh toán</strong></label>
        <input type="text" class="form-control" value="{{$order->form}}" readonly>
        <br>
        <label><strong>Mã giảm giá áp dụng</strong></label>
        <input type="text" class="form-control" value="{{$order->voucher}}" readonly>
        <br>
        <label><strong>Trạng thái đơn hàng</strong></label>
        <br>
        <select name="status" class="form-control" disabled>
            <option value="{{$order->status}}" selected>
                @if ($order->status == 1)
                Chờ duyệt
                @elseif($order->status == 2)
                Đã duyệt
                @elseif($order->status == 3)
                Đang giao hàng
                @elseif($order->status == 4)
                Đã thanh toán/nhận hàng
                @elseif($order->status == 5)
                Đã hủy
                @endif
            </option>
        </select>
    </div>
    <div class="card-footer">
        <div class="row">
            <div class="col-6 text-right">
                <a href="{{route('manage-order.index')}}" class="btn btn-danger">Quay về</a>
            </div>
            <div class="col-6 text-left">
                <a href="{{route('manage-order.edit', $order->id)}}" class="btn btn-secondary" data-toggle="tooltip" data-placement="bottom" title="Edit">
                    Sửa thông tin đơn hàng
                </a>
            </div>
        </div>
    </div>
</div>
@endsection