routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//authentication
// Route::get('manage-product','Backend\ProductController@index');
Auth::routes();
Route::get('logout', 'Auth\LoginController@logout')->name('logoutt');
Route::post('login', 'Auth\LoginController@authenticate')->name('loginn');

//socilite
//facebook
Route::get('login/facebook', 'Auth\LoginController@redirectToFacebookProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderFacebookCallback');
//google
Route::get('login/google', 'Auth\LoginController@redirectToGoogleProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderGoogleCallback');

//backend

//filter
Route::get('manage-product/search','Backend\ProductController@filter')->name('filter');
Route::get('manage-quotation/search','Backend\QuotationController@filter')->name('qfilter');
Route::get('filter-orders', 'Backend\OrderController@filter')->name('filter-orders');
Route::get('manage-code/search', 'Backend\CodeController@filter')->name('filter-code');
Route::get('manage-post/search', 'Backend\PostController@filter')->name('filter-post');
Route::get('manage-promotion/search','Backend\PromotionController@filter')->name('filter-promotion');

Route::get('manage-comments', 'Backend\CommentController@post_comment')->name('manage-comments');
Route::get('filter-user', 'Backend\UserController@filter')->name('filter-user');
Route::get('/home', 'Backend\HomeController@index')->name('home');
Route::resources([
    'manage-user' => 'Backend\UserController',
    'manage-product-category' => 'Backend\ProductCategoryController',
    'manage-product' => 'Backend\ProductController',
    'manage-post-category' => 'Backend\PostCategoryController',
    'manage-post' => 'Backend\PostController',
    'manage-tag' => 'Backend\TagController',
    'manage-banner' => 'Backend\BannerController',
    'manage-code' => 'Backend\CodeController',
    'manage-order' => 'Backend\OrderController',
    'manage-quotation' => 'Backend\QuotationController',
    'manage-footer-post' => 'Backend\FooterPostController',
    'manage-comment' => 'Backend\CommentController',
    'manage-file' => 'Backend\FileController',
    'manage-promotion'=> 'Backend\PromotionController'
]);


//frontend
// Route::get('search-product', 'Frontend\ProductController@search')->name('search_product');
Route::get('','Frontend\HomeController@index')->name('index');
Route::resource('index','Frontend\HomeController');
Route::resource('danh-muc','Frontend\ProductCategoryController');
Route::resource('post','Frontend\PostController');
Route::resource('san-pham','Frontend\ProductController');
Route::resource('cart','Backend\CartController');
Route::resource('order','Backend\OrderDetailController');
Route::resource('user','Frontend\UserController');
Route::resource('don-hang','Frontend\OrderController');
Route::resource('address','Backend\AddressController');
Route::resource('code','Frontend\CodeController');
Route::resource('manage-address','Frontend\AddressController');
Route::resource('footer-post','Frontend\FooterPostController');
Route::resource('tag','Frontend\TagController');
//quotation 
Route::resource('yeu-cau-bao-gia','Frontend\QuotationController');

Route::get('dia-chi','Backend\AddressController@create');
Route::get('tao-dia-chi','Backend\AddressController@createAddress');
Route::post('save-address','Backend\AddressController@storeAddressOnly');

Route::get('filter-order', 'Frontend\OrderController@filter')->name('filter-order');
Route::get('filter-product-cate/{id}', 'Frontend\ProductCategoryController@filter')->name('filter-product-cate');
Route::get('search', 'Frontend\HomeController@search')->name('search-product');
Route::post('filter-search', 'Frontend\HomeController@filterSearch')->name('filter-search');

//comments for post
Route::post('comments', 'Frontend\CommentController@store')->name('comment');

Route::post('comment-product', 'Frontend\CommentController@product')->name('comment-product');

Route::get('check-cart', 'Frontend\CheckcartController@index')->name('check-cart');
Route::get('list-cart', 'Frontend\CheckcartController@show')->name('list-cart');

Route::post('reply', 'Frontend\ReplyController@store')->name('reply');

Route::post('saving-data','Backend\AddressController@store');
Route::post('saving-order','Backend\AddressController@save');
Route::get('thanh-toan','Backend\AddressController@index');
Route::get('get-district-list','Backend\AddressController@getDistrictList');
Route::get('get-ward-list','Backend\AddressController@getWardList');



//change user password by themselve
Route::post('update-password','Frontend\UserController@updatePassword')->name('update-password');

//export data user 
Route::get('export', 'Backend\ExportController@export')->name('export');
Route::get('export-order', 'Backend\ExportOrderController@export')->name('export-order');
Route::get('export-product', 'Backend\ExportProductController@export')->name('export-product');
Route::get('export-code', 'Backend\ExportCodeController@export')->name('export-code');

app/Http/Controllers/Frontend/AddressController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Address;
use App\Models\Cart;
use App\Models\Province;
use App\Models\FooterPost;
use App\Models\District;
use App\Models\Ward;
use App\Models\Tag;
use App\Models\ProductCategory;
use Illuminate\Support\Facades\Auth;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::check())
        {
            $footerPost = FooterPost::where('status',1)->get();
            $address = Address::findOrFail($id);
            $provinces = Province::pluck("name","id");
            $cartlist = Cart::where('user_id',Auth::user()->id)->count();
            $cart = Cart::where('user_id',Auth::user()->id)->get();

            //hotTags in index
            $tags = Tag::all()->sortByDesc('views')->take(6);
            //hot tags in footer
            $tgs = Tag::all()->sortByDesc('views')->take(12);
            
            //get all active categogies
            $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                            ->OrderBy('order','desc')->get();
            
            return view('frontend.editAddress',compact('tags','tgs','categories','cart','cartlist','address','provinces','footerPost'));
        }
        return redirect()->route('index');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(Auth::check())
        {
            //validate
            $request->validate([
                'phone' => ['regex:/(01[2|6|8|9]|03[2|3|4|5|6|7|8|9]|05[6|8|9]|08[1|2|3|4|5|6|9|8]|09[0|1|2|3|4|2|6|7|8|9])+([0-9]{7})\b/']
            ]);
            
            //create address
            $province = Province::where('id',$request->get('province'))->first()->name;
            $district = District::where('id',$request->get('district'))->first()->name;
            $ward = Ward::where('id',$request->get('ward'))->first()->name;
            $add = $ward.", ".$district.", ".$province;

            $address = Address::findOrFail($id);
            $address->user_id = Auth::user()->id;
            $address->name = $request->get('name');
            $address->phone = $request->get('phone');
            $address->address = $add;
            $address->note = $request->get('note');
            $address->save();
            return back()->with('success','Thay đổi địa chỉ thành công');
        }
        return redirect()->route('index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/CheckcartController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Models\Checkcart;
use App\Models\Banner;
use App\Models\Product;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\User;
use App\Models\ProductCategory;
use App\Models\Post;
use Illuminate\Support\Facades\Auth;
use App\Models\Cart;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\FooterPost;
use App\Models\Tag;
class CheckcartController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $user=USer::all();
        $banner = Banner::all();
        $footerPost = FooterPost::where('status',1)->get();

        //hotTags in index
        $tags = Tag::all()->sortByDesc('views')->take(6);
        //hot tags in footer
        $tgs = Tag::all()->sortByDesc('views')->take(12);

        $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                    ->OrderBy('order','desc')
                                    ->get();

        $product = Product::where('status',1)->get();

        $posts = Post::where('status',1)->OrderBy('created_at','desc')->limit(5)->get();

        if(Auth::check()){
            $cartlist = Cart::where('user_id',Auth::user()->id)->count();
            $cart = Cart::where('user_id',Auth::user()->id)->get();
            return view('frontend.checkCart1', compact('tags','tgs','categories','product','banner','posts','cartlist','cart', 'user','footerPost'));
        }
        return view('frontend.checkCart1', compact('tags','tgs','categories','product','banner','posts','user','footerPost'));
    }
        
    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        //
    }
    
    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    // public function store(Request $request)
    
    
    /**
    * Display the specified resource.
    *
    * @param  \App\Checkcart  $checkcart
    * @return \Illuminate\Http\Response
    */
    public function show(Request $request)
    {
        $footerPost = FooterPost::where('status',1)->get();

        //hotTags in index
        $tags = Tag::all()->sortByDesc('views')->take(6);
        //hot tags in footer
        $tgs = Tag::all()->sortByDesc('views')->take(12);
        
        //get all active categogies
        $categories = ProductCategory::where([['parent_id', '=', 0],['status','=',1],])
                                        ->OrderBy('order','desc')->get();
        
        //get options
        $options = $request->get('option1');
        //seach by phone
        if($options == 0){

            $option =$request->get('data');
            $user=User::where('phone', $option)->get();

            if($user->isEmpty()){
                return back()->with('error','Số điện thoại sai hoặc chưa đăng kí tài khoản');
            }

            $order = Order::where('phone', $option)->get();
            $orderid = Order::select('id')->where('phone', $option)->get();
            
            if($order->isEmpty()){
                return back()->with('error','Chưa có đơn hàng nào trong giỏ hàng');
            }
            $orderid = $order->map->only(['id']);

            $productid = OrderDetail::where('orders_id', $orderid)->get();

            if(Auth::check()){
                $cartlist = Cart::where('user_id',Auth::user()->id)->count();
                $cart = Cart::where('user_id',Auth::user()->id)->get();
                return view('frontend.checkCart', compact('tags','tgs','categories','options','option','cartlist','cart', 'user', 'order', 'productid','footerPost'));
            }
            return view('frontend.checkCart', compact('tags','tgs','categories','options','option','user', 'order', 'productid','footerPost'));   
        }
        
        //search by email
        elseif($options == 1)
        {  
            $option = $request->get('data');

            $user = User::where('email', $option)->first();

            if($user === null){
                return back()->with('error', 'Email sai hoặc chưa đăng kí tài khoản');
            }

            $order = Order::where('user_id', $user->id)->get();

            if($order->isEmpty()){
                return back()->with('error','Chưa có đơn hàng nào trong giỏ hàng');
            }
            
            $orderid = $order->map->only(['id']);

            $productid = OrderDetail::where('orders_id', $orderid)->get();
            
            if(Auth::check()){

                $cartlist = Cart::where('user_id',Auth::user()->id)->count();
                $cart = Cart::where('user_id',Auth::user()->id)->get();
                return view('frontend.checkCart', compact('tags','categories','options','option','tgs','cartlist','cart', 'user', 'order', 'productid','footerPost'));
            }
            return view('frontend.checkCart', compact('tags','categories','tgs','options','option','user', 'order' , 'productid','footerPost')); 
        }
    }
    
    /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Checkcart  $checkcart
    * @return \Illuminate\Http\Response
    */
    public function edit(Checkcart $checkcart)
    {
        //
    }
    
    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Checkcart  $checkcart
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Checkcart $checkcart)
    {
        //
    }
    
    /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Checkcart  $checkcart
    * @return \Illuminate\Http\Response
    */
    public function destroy(Checkcart $checkcart)
    {
        //
    }
}
    

app/Http/Controllers/Frontend/CodeController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Models\Code;


class CodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
       //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/layouts/frontend/category.blade.php
@foreach ($categories as $item)
<div class="px-0 col-md-12">
    <div class="card">
        <div class="pl-3 card-header">
            <ul class="nav nav-pills nav-secondary" id="pills-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="pills-{{$item->id}}-tab" data-toggle="pill" href="#pills-{{$item->id}}" role="tab" aria-controls="pills-{{$item->id}}" aria-selected="true">{{$item->title}}</a>
                </li>
                @if (count($item->childs))
                @include('frontend.pillChild',['childs' => $item->childs])
                @endif
            </ul>
        </div>
        
        <div class="px-2 card-body">
            <div class="tab-content mt-2 mb-3" id="pills-tabContent">
                <div class="tab-pane fade show active" id="pills-{{$item->id}}" role="tabpanel" aria-labelledby="pills-{{$item->id}}-tab">
                    <!--Carousel Wrapper-->
                    <div class="owl-carousel owl-theme">
                        @foreach ($item->product as $pro)
                        @if ($pro->status == 1)
                        <div class="item">
                            <div class="card-product"> 
                                <a href="{{route('san-pham.show',$pro->slug)}}">
                                    <img class="img-fluid" style="height: 210px;" src="{{asset('images/'.json_decode($pro->filename)[0])}}" alt="Chania">
                                </a>
                                <div class="col">
                                    <div class="pt-3 title-card" style="height: 55px;">
                                        <a class="card-title" href="{{route('san-pham.show',$pro->slug)}}" style="height: 50px;">
                                            <h4 class="ellipsis">
                                                {{$pro->name}} 
                                            </h4>
                                        </a>    
                                    </div>
                                    <div class="text-left common-cost">
                                        <div class="col">
                                            <div class="row">
                                                @if (!empty($pro->promotion))               
                                                <p class="main-cost">
                                                    <b>{{number_format( $pro->promotion*1000, 0, ',', '.' )}}đ</b>
                                                </p>                
                                                <p class="pt-1 abondon-text-cost">
                                                    {{number_format( $pro->price*1000, 0, ',', '.' )}}đ
                                                </p>
                                                @else
                                                <p class="main-cost">
                                                    <b>{{number_format( $pro->price*1000, 0, ',', '.' )}}đ</b>
                                                </p>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-left">  
                                    </div>
                                    <div class="rating-star pb-2">
                                        <span class="fa fa-star @if(floatval($pro->star) > 1) checked @endif" id="star"></span>
                                        <span class="fa fa-star @if(floatval($pro->star) > 1.5) checked @endif" id="star"></span>
                                        <span class="fa fa-star @if(floatval($pro->star) > 2.5) checked @endif" id="star"></span>
                                        <span class="fa fa-star @if(floatval($pro->star) > 3.5) checked @endif" id="star"></span>
                                        <span class="fa fa-star @if(floatval($pro->star) > 4.5) checked @endif" id="star"></span>
                                    </div>
                                    <div class="row pb-3 icon-view-details">
                                        <a href="{{route('san-pham.show',$pro->slug)}}"> <div class="col" style="color: blue;">Xem chi tiết</div></a>
                                        @if (Auth::check())
                                        <form action="{{URL::route('cart.store')}}#pills-{{$item->id}}" method="post">
                                            @csrf
                                            <input type="text" value="{{Auth::user()->id}}" name="user_id" hidden>
                                            <input type="text" value="1" name="quantity" hidden>
                                            <input type="text" value="{{$pro->id}}" name="product_id" hidden>
                                            <input type="text" value="{{explode(',',$pro->size)[0]}}" name="size" hidden>
                                            <input type="text" value="{{explode(',',$pro->color)[0]}}" name="color" hidden>
                                            <button type="submit" class="btn-btn-cart">
                                                <i class="fas fa-cart-plus" style="color: #f09819;"></i>
                                            </button>
                                        </form>
                                        @else
                                        <a href="{{route('login')}}">
                                            <div class="product-btn" style="color: #f09819;">
                                                <i class="fas fa-cart-plus"></i>
                                            </div>
                                        </a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endif
                        
                        @endforeach 
                        @foreach ($product as $pro)
                        @if ($pro->productCategory->parent_id == $item->id && $pro->status == 1 && $pro->productCategory->status == 1)
                        <div class="item">
                            <div class="card-product"> 
                                <a href="{{route('san-pham.show',$pro->slug)}}">
                                    <img class="img-fluid" style="height: 210px;" src="{{asset('images/'.json_decode($pro->filename)[0])}}" alt="Chania">
                                </a>
                                <div class="col">
                                    <div class="pt-3 title-card" style="height: 55px;">
                                        <a class="card-title" href="{{route('san-pham.show',$pro->slug)}}" style="height: 50px;">
                                            <h4 class="ellipsis">
                                                {{$pro->name}}
                                            </h4>
                                        </a>
                                    </div>
                                    <div class="text-left common-cost">
                                        <div class="col">
                                            <div class="row">
                                                @if (!empty($pro->promotion))               
                                                <p class="main-cost">
                                                    <b>{{number_format( $pro->promotion, 0, ',', ' ' )}}.000đ</b>
                                                </p>                
                                                <p class="pt-1 abondon-text-cost">
                                                    {{number_format( $pro->price, 0, ',', ' ' )}}.000đ
                                                </p>
                                                @else
                                                <p class="main-cost">
                                                    <b>{{number_format( $pro->price, 0, ',', ' ' )}}.000đ</b>
                                                </p>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-left">  
                                    </div>
                                    <div class="rating-star pb-2">
                                        <span class="fa fa-star @if(floatval($pro->star) > 1) checked @endif" id="star"></span>
                                        <span class="fa fa-star @if(floatval($pro->star) > 1.5) checked @endif" id="star"></span>
                                        <span class="fa fa-star @if(floatval($pro->star) > 2.5) checked @endif" id="star"></span>
                                        <span class="fa fa-star @if(floatval($pro->star) > 3.5) checked @endif" id="star"></span>
                                        <span class="fa fa-star @if(floatval($pro->star) > 4.5) checked @endif" id="star"></span>
                                    </div>
                                    <div class="row pb-3 icon-view-details">
                                        <a href="{{route('san-pham.show',$pro->slug)}}"> <div class="col" style="color: blue;">Xem chi tiết</div></a>
                                        @if (Auth::check())
                                        <form action="{{URL::route('cart.store')}}#pills-{{$item->id}}" method="post">
                                            @csrf
                                            <input type="text" value="{{Auth::user()->id}}" name="user_id" hidden>
                                            <input type="text" value="1" name="quantity" hidden>
                                            <input type="text" value="{{$pro->id}}" name="product_id" hidden>
                                            <input type="text" value="{{explode(',',$pro->size)[0]}}" name="size" hidden>
                                            <input type="text" value="{{explode(',',$pro->color)[0]}}" name="color" hidden>
                                            <button type="submit" class="btn-btn-cart">
                                                <i class="fas fa-cart-plus" style="color: #f09819;"></i>
                                            </button>
                                        </form>
                                        @else
                                        <a href="{{route('login')}}">
                                            <div class="product-btn" style="color: #f09819;">
                                                <i class="fas fa-cart-plus"></i>
                                            </div>
                                        </a>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endif
                        @endforeach
                    </div>
                </div>
                @if (count($item->childs))
                @include('frontend.pillContentChild',['childs' => $item->childs])
                @endif
            </div>
        </div>
    </div>
</div>
@endforeach

resources/views/layouts/frontend/hotKey.blade.php
<div class="product pb-lg-4">
    <div class="card-body">
        <h2 style="border-left: 4px solid orange; padding-left: 10px;"><b>TỪ KHÓA HOT</b></h2>
    </div>
    <div class="pl-4 col-md-12">
        <div class="row">
            @foreach ($tags as $tag)
            <div class="mb-3 col-6 col-md-6 col-lg-2">
                <button type="button" class="btn-gradient{{$i++}}"><a href="{{route('tag.show',$tag->slug)}}" style="color:white">{{$tag->name}}</a></button>
            </div>
            @endforeach
        </div>
    </div>
</div>

resources/views/layouts/frontend/userCategory.blade.php
<div class="py-4 col-3 d-lg-block d-none">
    <div class="list-group" id="text-hidden-category">
        <a href="{{route('user.show',Auth::user()->id)}}" class="list-group-item list-group-item-action" style="margin: 5px 5px 0px 0px; color: #f09819;">
            <b><i class="fas fa-user"></i> Thông tin tài khoản</b>
        </a>
        <a href="{{route('user.show',Auth::user()->id)}}" class="list-group-item list-group-item-action">
            <i class="fas fa-circle" style="margin-right: 3px;margin-top: 7px; font-size: 6px;"></i>Thông tin cá nhân
        </a>
        <a href="{{route('user.edit',Auth::user()->id)}}" class="list-group-item list-group-item-action">
            <i class="fas fa-circle" style="margin-right: 3px;margin-top: 7px; font-size: 6px;"></i>Thay đổi mật khẩu
        </a>
        <a class="list-group-item list-group-item-action" style="margin: 5px 5px 0px 0px; color: #f09819;">
            <i class="fas fa-file-invoice-dollar"></i> &nbsp; Quản lý mua hàng
        </a>
        <a href="{{route('order.show',Auth::user()->id)}}" class="list-group-item list-group-item-action">
            <i class="fas fa-circle" style="margin-right: 3px;margin-top: 7px; font-size: 6px;"></i>Lịch sử đơn hàng
        </a>
        <a href="{{url('dia-chi')}}" class="list-group-item list-group-item-action">
            <i class="fas fa-circle" style="margin-right: 3px;margin-top: 7px; font-size: 6px;"></i>Thiết lập địa chỉ
        </a>
        <a href="{{route('logoutt')}}" class="list-group-item list-group-item-action">
            <i class="fas fa-circle" style="margin-right: 3px;margin-top: 7px; font-size: 6px;"></i>Đăng xuất
        </a>
    </div>
</div>